[package]
name = "typst-spell-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
termcolor = "1.4.1"
